version: "3.3"

services:
  login-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - LOGIN_PORT=80
      - DB_HOSTNAME=mysql
      - DB_PORT=3306
      - DB_DATABASE=canary
      - DB_USERNAME=canary
      - DB_PASSWORD=canary
      - SERVER_NAME=Canary
      - SERVER_IP=127.0.0.1
      - SERVER_PORT=7172
      - SERVER_LOCATION=NL
