on: push
name: Golang Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Go Modules
        uses: cedrickring/golang-action@1.6.0
        env:
          GO111MODULE: "on"

      - name: Custom project path
        uses: cedrickring/golang-action@1.6.0
        env:
          PROJECT_PATH: "/src"

      - name: Run tests
        uses: cedrickring/golang-action@1.6.0
        with:
          args: go test ./tests -v

      - name: run
        uses: cedrickring/golang-action@1.6.0